version: "3.8"

services:
  dev:
    restart: unless-stopped
    build:
      context: .
      target: develop
    ports:
      - "9229:9229"
      - "${PORT}:${PORT}"
    expose:
      - "9229"
      - "${PORT}"
    volumes:
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./src:/usr/src/app/src
    env_file:
      - .env.develop
    environment:
      - PORT=${PORT}
      - NODE_ENV=develop
  prod:
    build:
      context: .
      target: production
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    expose:
      - "${PORT:-8080}"
    environment:
      - PORT=${PORT:-8080}
      - NODE_ENV=production
